//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoctorTb()
        {
            this.ProjectTbs = new HashSet<ProjectTb>();
        }
    
        public int id { get; set; }
        public string DoctorName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Maximum_of_Reg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTb> ProjectTbs { get; set; }
    }
}
