//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnew.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTb()
        {
            this.RegisterTbs = new HashSet<RegisterTb>();
        }
    
        public int projectId { get; set; }
        public Nullable<int> DocId { get; set; }
        [Required]

        public string ProjectName { get; set; }
        [Required]

        public string Projectcode { get; set; }
        public string Description { get; set; }
    
        public virtual DoctorTb DoctorTb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterTb> RegisterTbs { get; set; }
    }
}
