//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gnew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterTb
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateReg { get; set; }
        public string StudentName { get; set; }
        public int StudentRegNo { get; set; }
        public Nullable<int> projectId { get; set; }
        public string Description { get; set; }
    
        public virtual ProjectTb ProjectTb { get; set; }
    }
}
